version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./data:/app/data
      - ./timeline.json:/app/timeline.json
    environment:
      - FLASK_ENV=development
    command: ["python", "-m", "cli.src.main", "serve", "--port", "3001"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:3001

  # Optional: Add a database service if needed in the future
  # database:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_DB: codebase_timeline
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: